//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulacit_parkingC_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        internal string cardNumber;
        internal char isActive;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Vehicles = new HashSet<Vehicles>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string identification { get; set; }
        public string card_number { get; set; }
        public string role { get; set; }
        public string password { get; set; }
        public string first_login { get; set; }
        public string PasswordChanged { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehicles> Vehicles { get; set; }
        public DateTime DateOfBirth { get; internal set; }

        public static implicit operator User(Users v)
        {
            throw new NotImplementedException();
        }
    }
}
